# +----------------------------------+
# | Supreme Machines                 |
# | Sensorimotor Local Tests         |
# | Matthias Kubisch                 |
# | kubisch@informatik.hu-berlin.de  |
# | December 2018                    |
# +----------------------------------+

VariantDir('build', 'src', duplicate=0)

env = Environment( PROJECT_NAME = 'sensorimotor_tests'
                 , CCFLAGS      = ['-Wall' , '-Wextra']
#                , LIBS         = ['framework'],
                 , CPPPATH      = ['#src', '#../firmware']
                 , CXXFLAGS     = ['-std=c++0x']
                 )

tests = env.Program('run_tests', [ 'build/tests_main.cpp'
                                 , 'build/communication_tests.cpp'
                                 , 'build/median3_tests.cpp'
                                 , 'build/lowpass_tests.cpp'
                                 , 'build/bitscale_tests.cpp'
                                 ])
